apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pp191225-api

resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml

helmCharts:
  - name: pp191225-api-service
    repo: https://thang2k6adu.github.io/backend-service-charts
    version: 0.1.0
    releaseName: dev
    namespace: pp191225-api
    valuesFile: values.yaml
