apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{SERVICE_NAME}}

resources:
  - namespace.yaml

helmCharts:
  - name: {{CHART_NAME}}
    repo: {{CHART_REPO}}
    version: 0.1.0
    releaseName: {{RELEASE_NAME}}
    namespace: {{SERVICE_NAME}}
    valuesFile: values.yaml
