apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: livekit-server

resources:
  - configmap.yaml
  - sealed-secret.yaml
  - namespace.yaml

helmCharts:
  - name: backend-service-chart
    repo: https://thang2k6adu.github.io/backend-service-charts
    version: 0.1.0
    releaseName: dev
    namespace: livekit-server
    valuesFile: values.yaml
