service:
  name: pp191225-api
  releaseName: dev
  chartRepo: https://thang2k6adu.github.io/backend-service-charts
  # -> nó sẽ thành dev-pp191225-api trong k8s deployment
  # namespace sẽ tự động = service.name

image:
  repository: ghcr.io/thang2k6adu/pp191225-be/be
  tag: "91776ad92b4761c49707ecfc81efb42e196e6528"
  pullPolicy: Always

imagePullSecrets: []

replicas: 2

network:
  ingress: false
  port: 3000
  domain: pp191225.api.thang2k6adu.com

resources:
  cpu:
    request: 200m
    limit: 1000m
  memory:
    request: 256Mi
    limit: 512Mi

autoscaling:
  enabled: true
  min: 2
  max: 10
  cpuTarget: 70
  memoryTarget: 80

healthcheck:
  liveness:
    path: /api/health

  readiness:
    path: /api/health

  startup:
    path: /api/health

storage:
  volumes:
    - name: tmp
      mountPath: /tmp
      type: emptyDir
    - name: cache
      mountPath: /app/cache
      type: emptyDir

persistence:
  enabled: false
  size: 1Gi
  mountPath: /app/data
