apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{SERVICE_NAME}}

resources:
  - namespace.yaml

helmCharts:
  - name: livekit-server
    repo: https://helm.livekit.io
    version: 1.16.0
    releaseName: dev
    namespace: {{SERVICE_NAME}}
    valuesFile: values.yaml